webserver:
  #apache with python
  build: ./docker_files/webserver
  ports:
    - "8000:80"
  volumes:
    - ./src:/var/www/portal

elasticsearch:
  image: elasticsearch:2.1
  ports:
    - "9200:9200"
  # enable CORS
  command: elasticsearch -Des.http.cors.enabled=true -Des.http.cors.allow-origin="*"
