webserver:
  build: ./docker_files/node
  ports:
    - "8000:8000"
  #working_dir must match dir we mount host volume to
  volumes:
    - ./:/usr/src/app
  working_dir: /usr/src/app
  #correctly install bower, node packages, and starts server
  command: bash -c "npm install --unsafe-perm && bower --allow-root install && node server.js"

elasticsearch:
  image: elasticsearch:2.1
  ports:
    - "9200:9200"
