webserver:
  #apache with python
  # To build image, run from project root: docker build -t webserver docker_files/webserver
  image: webserver:latest
  ports:
    - "8000:80"
  links:
    - elasticsearch:elasticsearch
  volumes:
    - ./src:/var/www/portal
  command: /usr/sbin/apache2ctl -D FOREGROUND

elasticsearch:
  image: elasticsearch:2.1
  ports:
    - "9200:9200"
  # enable CORS
  command: elasticsearch -Des.http.cors.enabled=true -Des.http.cors.allow-origin="*"
