webserver:
  build: ./docker_files/node
  ports:
    - "8000:8000"
  # working_dir must match dir we mount host volume to
  volumes:
    - ./:/usr/src/app
  working_dir: /usr/src/app

  # install bower, node packages, and starts server
  # --unsafe-perm option needed on npm to install bower correctly w/docker
  # --allow-root needed when using bower w/docker
  # Note: Currently, portal_init.sh only sets basic environment vars for dev environment.
  #       It will only run if PORTAL_ROOT environment var does not exist.
  #       It should only be run once, when project first installed.
  command: bash -c "bash portal_init.sh && npm update --unsafe-perm && npm start"

elasticsearch:
  image: elasticsearch:2.1
  ports:
    - "9200:9200"
  # enable CORS
  command: elasticsearch -Des.http.cors.enabled=true -Des.http.cors.allow-origin="*"
