webserver:
  image: httpd:2.4
  ports:
    - "80:80"
  volumes:
    - ./src/client:/usr/local/apache2/htdocs

elasticsearch:
  image: elasticsearch:2.1
  ports:
    - "9200:9200"
  # enable CORS
  command: elasticsearch -Des.http.cors.enabled=true -Des.http.cors.allow-origin="*"
